version: '3.8'

services:
  user_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - PORT=5001
      - MONGO_URI=mongodb://mongo:27017/user-service
      - JWT_SECRET=your-user-service-jwt-secret
    depends_on:
      - mongo
    networks:
      - healthcare_network

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - user_mongo_data:/data/db
    networks:
      - healthcare_network

networks:
  healthcare_network:
    driver: bridge

volumes:
  user_mongo_data: